CREATE TABLE uuser
(
    id       bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) UNIQUE,
    mail     varchar(254) UNIQUE,
    password varchar NOT NULL,
    role     varchar NOT NULL,
    CONSTRAINT email_valid CHECK (mail ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}$')
);

CREATE TABLE subscription
(
    is_friend     bool NOT NULL,
    subscriber_id bigint REFERENCES uuser (id),
    publisher_id  bigint REFERENCES uuser (id),
    PRIMARY KEY (subscriber_id, publisher_id)
);

CREATE TABLE post
(
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    header       varchar(200) NOT NULL,
    text         varchar(200) NOT NULL,
    picture_path varchar NOT NULL,
    created_at   timestamp NOT NULL,
    user_id      bigint REFERENCES uuser (id)
);

CREATE TABLE message
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id   bigint REFERENCES uuser (id),
    receiver_id bigint REFERENCES uuser (id),
    text        varchar(500) NOT NULL,
    sent_at     timestamp NOT NULL
);
